sudo: false
cache: bundler

language: ruby
rvm:
  - 2.1

install: gem install github-pages html-proofer
script:
  - jekyll build
  - htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
