# Jekyll
gems:
  - jekyll-redirect-from

# Custom
siteTitle: DDuarte
siteDescription: Personal site of Duarte Duarte
avatar: /img/avatar.png
background: /img/background.jpg
description: Hi. I'm Duarte Duarte, a software engineering student @ FEUP from Porto, Portugal.
resumeFile: docs/cv.pdf

icons:
  - icon: page
    link: resume.html
  - icon: social-github
    link: http://www.github.com/DDuarte
  - icon: social-linkedin
    link: https://www.linkedin.com/in/dduarted
  - icon: social-twitter
    link: https://twitter.com/duarteduarte0

projects:
  - title: TrinityCore
    link: https://github.com/TrinityCore/TrinityCore
  - title: NeCG|FEUP
    link: https://github.com/necg
  - title: Jekyll Configurable Site
    link: https://github.com/DDuarte/JekyllConfigurablePersonalSite
