# Jekyll
gems:
  - jekyll-redirect-from

# Custom
siteTitle: DDuarte
siteDescription: Personal site of Duarte Duarte
avatar: /img/avatar.png
background: /img/background.jpg
description: Hi. I'm Duarte Duarte, a software engineering student @ FEUP from Porto, Portugal.
resumeFile: docs/cv.pdf

icons:
  - icon: page-pdf
    title: Resume
    link: resume.html
  - icon: social-github
    title: Github
    link: http://www.github.com/DDuarte
  - icon: social-linkedin
    title: LinkedIn
    link: https://www.linkedin.com/in/dduarted
  - icon: social-twitter
    title: Twitter
    link: https://twitter.com/duarteduarte0

projects:
  - name: TrinityCore
    title: TrinityCore Open Source MMO Framework
    link: https://github.com/TrinityCore/TrinityCore
  - name: NeCG|FEUP
    title: Computer Graphics Student Group
    link: https://github.com/necg
  - name: Jekyll Configurable Site
    link: https://github.com/DDuarte/JekyllConfigurablePersonalSite
